version: "3"
services:
  backend:
    container_name: backend
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: backend
    volumes:
      - data-volume:/data/db
volumes:
  data-volume: